# Generated by Django 4.1.3 on 2022-12-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='enable_hls',
            field=models.BooleanField(default=False),
        ),
    ]
